#! /bin/bash
#----------------
#  RunLawn
#---------------
echo "compiling Lawn.java"
javac Lawn.java>&Lawn-errs
echo "running Lawn.class"
java Lawn<Lawn-in Lawn>Lawn-out
echo "deleting Lawn.class"
rm Lawn.class
